language: c++
compiler:
  - gcc
  - clang
script: make
notifications:
    irc:
        channels:
            - "irc.freenode.org#wrench-lang"
        template:
            - "[%{commit} : ${author}] ${message}"
            - "%{build_url}"
        skip_join: true
